### ISSUE TITLE
Where to get the type detail description of data?

### ISSUE THREAD

**Issue by GravityMsc** [germanrcuriel/assetto-corsa-server-udp2ws#18]
https://github.com/germanrcuriel/assetto-corsa-server-udp2ws/blob/d9dab592fe963e2a8954a5e2d786e0c7b4a2a566/src/udp/types.js#L1

I have not found any useful docs except [AC Remote Telemetry Documentation](https://docs.google.com/document/d/1KfkZiIluXZ6mMhLWfDX1qAGbvhGRC3ZUzjVIt5FQpp4/pub). But it doesn't show these types. 
And I have another question, the doc told me I should use 9996, but you use plugin address port and local port of server_cfg.ini to receive and send data. Which is right?

**Comment by germanrcuriel** [comment]
This project is not using AC Remote Telemetry. If you want to use that one you can check https://github.com/rickwest/ac-remote-telemetry-client instead

**Comment by GravityMsc** [comment]
In other words, this is an AC plugin for data. The other one is made by using AC official udp port. Am I right?
But could you tell me where to find the description of these types, any document or just analyze udp data?

**Comment by germanrcuriel** [comment]
This is an AC Server plugin that transforms UDP information in a bidirectional way through WebSockets. The Remote Telemetry 9996 port is used to connect to an Assetto Corsa game not to a server.

Both are using official UDP protocols but they use different information.

You can take a look at the Readme to see the information you can send / receive using AC Dedicated Server UDP protocol. Just tried to search the original place this was published and looks like it was removed.

**Comment by GravityMsc** [comment]
Thanks for your reply.
