### ISSUE TITLE
How to setup assetto corsa server

### ISSUE THREAD

**Issue by truoss** [germanrcuriel/assetto-corsa-server-udp2ws#2]
Hello Germán,

at first i´m not the node.js, socket pro, so the problem is mainly me :) and thanks for the work you put into this project. I already learned a lot.

What i want to achieve in my Project:
I would like to collect the car positions of the player driving on my server, like all the live maps out there. But i want to learn to do it my self. Than i found your project and want to give it a try and build my on top of it.

Now i´m two days in and i´m at the point where I could go crying into my bed, because i can´t get it to work.

This is what i have done so far:
![server_plugin](https://user-images.githubusercontent.com/6495430/46112526-31b1a080-c1eb-11e8-900d-e2c3b6869e2c.jpg)
![server_setting](https://user-images.githubusercontent.com/6495430/46112530-35ddbe00-c1eb-11e8-808d-55fb995b35f7.jpg)
![config](https://user-images.githubusercontent.com/6495430/46112548-42faad00-c1eb-11e8-9d4c-322af635f03d.jpg)

for test purpose i wrote this:

```
<!DOCTYPE

 html>
  <meta charset="utf-8" />
  <title>WebSocket Test</title>
  <script src="http://localhost:30000/socket.io/socket.io.js"></script>
	<script>
	  var socket = io('http://localhost:30000');
	  socket.emit('authenticate', 'admin');
	  socket.emit('broadcast_message', 'Message sent from udp2ws');
	  socket.emit('get_car_info', 'requestCarInfo');
	  socket.emit('get_session_info', 'requestSessionInfo');
	  socket.emit('restart_session', 'restartSession');
	  socket.emit('chat', {'car_id' : 0, 'message' : 'test chat message'});
	  socket.on('console', (messageObject) => { console.log(messageObject.message) });
	  socket.on('chat', (data) => { console.log(data) })
	</script>
  
  <h2>WebSocket Test</h2>

  <div id="output"></div>
```

ac server is running and i can drive on it. When i press F5, in the chrome browser, I get this:

> createClient: 11000
createServer: 8004
udp_listening
Connected
postAuthenticate
Connected
postAuthenticate
Private Action: broadcast_message Message sent from udp2ws
Public Action: get_car_info requestCarInfo
Public Action: get_session_info requestSessionInfo
Private Action: restart_session restartSession
{ car_id: 0, message: 'test chat message' }

So if think i have an connection with the webpage and the nodejs, but i do not get events or response from the acServer.

I hope you could see what i´m doing wrong.

Regards,
Timo

**Comment by germanrcuriel** [comment]
Sorry for the very late response @truoss.

```js
  var socket = io('http://localhost:30000');
  socket.emit('authenticate', 'admin');
  socket.emit('broadcast_message', 'Message sent from udp2ws');
  socket.emit('get_car_info', 1); // Here you need to use a car ID number
  socket.emit('get_session_info', 1); // Here you need to use an optional session ID https://github.com/germanrcuriel/assetto-corsa-server-udp2ws#session-types
  socket.emit('restart_session'); // No second argument needed
  socket.emit('send_message', 0, 'test chat message'); // To send a message to a specific driver you need to use send_message command
  socket.on('console', (messageObject) => { console.log(messageObject.message) });
  socket.on('chat', (data) => { console.log(data) })
```

Also, to get events from the server you need to enable the realtime report by doing

```js
  socket.emit('enable_realtime_report', 500); // To get updates every 500 milliseconds
```

Hope it helps and sorry again for the late response
