### ISSUE TITLE
Upgrade to Socket.IO 4.x

### ISSUE THREAD

**Issue by ccidral** [germanrcuriel/assetto-corsa-server-udp2ws#23]
First thanks for this amazing work!

Is it possible to upgrade Socket.IO to version 4.x so that we can use newer client versions?

**Comment by germanrcuriel** [comment]
Hello @ccidral

I could definitely upgrade Socket.IO but it will take me some time to do it. Hope it is not urgent 😃

**Comment by ccidral** [comment]
No worries, not urgent at all.

**Comment by germanrcuriel** [comment]
Finally done! Very sorry for the huge delay @ccidral
