### ISSUE TITLE
I can't run udp2ws

### ISSUE THREAD

**Issue by farisrwx** [germanrcuriel/assetto-corsa-server-udp2ws#5]
everytime i try to ./udp2ws i get this error ..

dgram.js:455
    throw new ERR_INVALID_ARG_TYPE('buffer',
    ^
TypeError [ERR_INVALID_ARG_TYPE]: The "buffer" argument must be one of type Buffer, Uint8Array, or string. Received type object
    at sliceBuffer (dgram.js:455:11)
    at Socket.send (dgram.js:557:16)
    at ACSP.send (/snapshot/assetto-corsa-server-udp2ws/lib/udp/acsp.js:0:0)
    at Socket.emit (events.js:196:13)
    at dgram.js:321:14
    at processTicksAndRejections (internal/process/task_queues.js:84:9)
    at process.runNextTicks [as _tickCallback] (internal/process/task_queues.js:59:3)
    at Function.Module.runMain (pkg/prelude/bootstrap.js:1317:13)
    at internal/main/run_main_module.js:17:11

**Comment by germanrcuriel** [comment]
Hello @farissx!

Do you have both Assetto Corsa Dedicated Server and udp2ws running in the same machine?

If yes, can you copy your `udp2ws.ini` and `cfg/server_cfg.ini` file contents here? (Remember to remove any password you have set)

**Comment by farisrwx** [comment]
Hi @germanrcuriel 

Yes the Assetto Corsa Server and the udp2ws running in the same VPS. 

udptws.ini: https://hastebin.com/ulocikesoh.ini
server_cfg.ini: https://hastebin.com/bakixemowi.ini

I don't really know if the ports are set up correctly or no. 
Also to let you know i use https://github.com/JustaPenguin/assetto-server-manager to start the 
server .. 
when i restart the server through the Manager .. the ports in server_cfg.ini just randomly changed to another port. 
Maybe that's why udp2ws is not working idk.. 
But there are some options in the Manager here: http://prntscr.com/rje6oj

**Comment by germanrcuriel** [comment]
@farissx Maybe I need to update the comments in `udp2ws.ini` file so they are less confusing.

```ini
[ACPLUGIN]
; Proxy the AC server protocol on this port, so multiple plugins may be chained (this is equivalent to UDP_PLUGIN_LOCAL_PORT in server_cfg.ini)
proxyPluginLocalPort = 14003
; Proxy the AC server protocol on the following port, so plugins may be chained (this is equivalent to UDP_PLUGIN_ADDRESS in server_cfg.ini)
proxyPluginPort = 14004

; UDP port the plugin sends to (UDP_PLUGIN_LOCAL_PORT)
sendPort = 14001
; UDP port the plugin receives from. (UDP_PLUGIN_ADDRESS)
receivePort = 14002
```

Then, if you need to use another plugin (stracker, Kissmyrank, etc) you can use `proxyPluginLocalPort` and `proxyPluginPort` values in their config

**Comment by farisrwx** [comment]
Thank you so much, I got it working :D http://prntscr.com/rjir2k
